const DataProduct = {
    properties: [
        {
            _id: "dalia_pink_dress",
            index: 0,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Dluga-sukienka-do-treningu-DALIA-PINK-80_4.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 1,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_top-do-treningu-COLIA-BLACK-116_1.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 2,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Body-do-treningu-VELSA-BLACK-84_4.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 3,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Dluga-sukienka-do-treningu-OLIMPIA-83_1.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 4,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Dluga-sukienka-do-treningu-DALIA-PINK-80_4.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 5,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_top-do-treningu-COLIA-BLACK-116_1.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 6,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Body-do-treningu-VELSA-BLACK-84_4.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
        {
            _id: "dalia_pink_dress",
            index: 7,
            price: 50 + "$", 
            picture: "https://shop-justynamakowska.iai-shop.com/pol_pm_Dluga-sukienka-do-treningu-OLIMPIA-83_1.jpg",
            name: "DALIA DRESS",
            color: "Pink",
            fabric : "Lycra",
        },
    ]

}
export default DataProduct;